apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://globalbank-database:3306/bankingapp"
  SERVER_PORT: "8100"
  SPRING_SERVER_SERVLET_CONTEXT_PATH: "/api"