apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-init
type: Opaque
stringData:
  init-user.sql: |
      CREATE USER dev-user WITH PASSWORD 'devpass';
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO devuser;
