apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-init
type: Opaque
stringData:
  init-user.sql: |
    DO
    $$
    DECLARE
      user_exists INTEGER;
    BEGIN
      SELECT COUNT(*) INTO user_exists FROM pg_catalog.pg_roles WHERE rolname = '${dev-user}'';
      IF user_exists = 0 THEN
        CREATE USER ${dev-user} WITH PASSWORD '${dev-password}';
        CREATE DATABASE bankingapp OWNER ${dev-user};
        CREATE DATABASE bankingapp2 OWNER ${dev-user};
        GRANT ALL PRIVILEGES ON DATABASE bankingapp TO ${dev-user};
      END IF;
    END
    $$;
