apiVersion: v1
kind: ConfigMap
metadata:
  name: globalbank-postgresql-init
data:
  init-user.sh: |
    #!/bin/bash
    set -e

    LOG_FILE="/tmp/init-script.log"
    echo "*** Starting custom init script ***" | tee -a $LOG_FILE

    echo "Creating user and database..." | tee -a $LOG_FILE

    psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL >> $LOG_FILE 2>&1
      \echo '*** Running SQL statements ***'
      CREATE USER devuser WITH PASSWORD 'devpass';
      CREATE DATABASE bankingapp;
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO devuser;
      \echo '*** Finished SQL statements ***'
    EOSQL

    echo "*** Finished custom init script ***" | tee -a $LOG_FILE
