apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-init
type: Opaque
stringData:
  init-user.sql: |
      CREATE USER ${dev-user} WITH PASSWORD '${dev-password}';
      CREATE DATABASE bankingapp OWNER ${dev-user};
      CREATE DATABASE bankingapp2 OWNER ${dev-user};
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO ${dev-user};
