apiVersion: v1
kind: ConfigMap
metadata:
  name: globalbank-postgresql-init
data:
  init-user.sql: |
      \pset pager off
      \o /tmp/init-script.log
      \echo '*** Running init-user.sql ***'
      CREATE USER devuser WITH PASSWORD 'devpass';
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO devuser;
      SELECT 1/0;
      \echo '*** init-user.sql completed ***'
