apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-init
data:
  init-user.sql: |
      CREATE USER devuser WITH PASSWORD 'devpass';
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO devuser;
