apiVersion: v1
kind: ConfigMap
metadata:
  name: globalbank-postgresql-init
data:
  init-user.sql: |
      \pset pager off
      \echo '*** Running init-user.sql ***'
      CREATE USER devuser WITH PASSWORD 'devpass';
      GRANT ALL PRIVILEGES ON DATABASE bankingapp TO devuser;
      \echo '*** init-user.sql completed ***'
