apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.host.name }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.applications.backend }}
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.applications.frontend }}
                port:
                  number: 80