global:
  postgresql:
    database: bankingapp
    username: devuser
    existingSecret: globalbank-postgresql-credentials

postgresql:
  replicaCount: 2
  initdbScriptsSecret: globalbank-postgresql-init