global:
  postgresql:
    database: bankingapp
    username: bankuser
    repmgrUsername: repmgr
    existingSecret: globalbank-postgresql-credentials

postgresql:
  replicaCount: 2
  initdbScripts: globalbank-postgresql-init