# globalbank-postgresql/values.yaml
postgresql:
  global:
    postgresql:
      auth: 
        database: bankingapp
        username: bankuser
        existingSecret: globalbank-postgresql-credentials
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "dev-password"
          replicationPasswordKey: "replication-password"