global:
  postgresql:
    database: bankingapp
    username: "devuser"
    repmgrUsername: "repuser"
    existingSecret: globalbank-postgresql-credentials

postgresql:
  replicaCount: 2
  initdbScriptsSecret: globalbank-postgresql-init