postgresql:
  auth:
    existingSecret: postgresql-credentials
    existingSecretKeys:
      postgresPassword: postgresql-postgres-password  # admin password key
      replicationPassword: postgresql-replication-password
      password: postgresql-password                   # user password key
    username: devuser
    database: bankingapp

primary:
  persistence:
    size: 8Gi

replica:
  replicaCount: 2
  persistence:
    size: 8Gi