# globalbank-postgresql/values.yaml
postgresql-ha:
  global:
    postgresql:
      database: bankingapp
      username: bankuser
      repmgrUsername: repmgr
      existingSecret: globalbank-postgresql-credentials
    pggpool:
      adminUsername: "sr_admin_user"
      adminPassword: ""
      srCheckUsername: "sr_check_user"
      srCheckPassword: ""
      existingSecret: "globalbank-postgresql-pgpool-passwd"

  postgresql:
    replicaCount: 3
    initdbScriptsCM: globalbank-postgresql-init
    maxConnections: 1000

  pgpool:
    enabled: true
    srCheckDatabase: bankingapp
    numInitChildren: 200       # handle more client connections
    maxPool: 2                # allow more backend connections per child
    maxClientConn: 400        # total client connections allowed
    connectionLifeTime: 120 # seconds, adjust as needed
    clientIdleLimit: 120    # seconds
    enablePoolHba: true