postgresql:
  database: bankingapp
  initdbScriptsCM: globalbank-postgresql-init

auth:
    existingSecret: globalbank-postgresql-credentials

primary:
  persistence:
    size: 8Gi

replica:
  replicaCount: 2
  persistence:
    size: 8Gi